services:
  - type: web
    name: foodapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn foodapp.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: foodapp.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
