# Generated by Django 5.2.4 on 2025-07-13 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=30)),
                ('location', models.CharField(default='other', max_length=30)),
                ('image', models.FileField(default='default.jpg', upload_to='items/shops/')),
                ('bio', models.CharField(default='', max_length=100)),
                ('rating', models.IntegerField(choices=[(0, '0 Stars'), (1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=0)),
                ('time', models.JSONField(default=dict)),
                ('email', models.EmailField(default='', max_length=100)),
                ('number1', models.CharField(default='', max_length=13)),
                ('number2', models.CharField(default='', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='other', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='other', max_length=30)),
                ('image', models.FileField(default='default.jpg', upload_to='shopitems/')),
                ('section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.sections')),
            ],
        ),
        migrations.CreateModel(
            name='ShopItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='other', max_length=30)),
                ('image', models.FileField(default='default.jpg', upload_to='items/shops/')),
                ('desc', models.CharField(default='', max_length=100)),
                ('rating', models.IntegerField(choices=[(0, '0 Stars'), (1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=0)),
                ('hotel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.hotels')),
                ('section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.items')),
            ],
        ),
    ]
