# Generated by Django 5.2.4 on 2025-07-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hotels_managers_hotels_owner_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='time',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
