# Generated by Django 5.2.4 on 2025-07-14 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_hotels_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitems',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.items'),
        ),
        migrations.AlterField(
            model_name='shopitems',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.sections'),
        ),
    ]
